In [ ]:
# https://www.daleseo.com/sort-quick/

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])

In [3]:
a[0:2]

array([1, 2])

In [2]:
import numpy as np
import pandas as pd
import re
import torch

In [6]:
tr = torch.randn(2,3,4)
tr

tensor([[[ 1.4779, -1.9527,  0.5818,  0.7369],
         [-1.5111,  0.6199,  1.1163,  0.8683],
         [-0.6130,  2.4811, -0.9924, -0.4231]],

        [[-1.0748,  0.0165, -0.1008,  0.1572],
         [ 0.9345, -0.3954,  0.8339,  0.2443],
         [-1.6820, -0.4767, -0.6974,  0.0771]]])

In [8]:
torch.squeeze(tr, dim = 1)

tensor([[[ 1.4779, -1.9527,  0.5818,  0.7369],
         [-1.5111,  0.6199,  1.1163,  0.8683],
         [-0.6130,  2.4811, -0.9924, -0.4231]],

        [[-1.0748,  0.0165, -0.1008,  0.1572],
         [ 0.9345, -0.3954,  0.8339,  0.2443],
         [-1.6820, -0.4767, -0.6974,  0.0771]]])

In [9]:
tr.view(2, 12 )

tensor([[ 1.4779, -1.9527,  0.5818,  0.7369, -1.5111,  0.6199,  1.1163,  0.8683,
         -0.6130,  2.4811, -0.9924, -0.4231],
        [-1.0748,  0.0165, -0.1008,  0.1572,  0.9345, -0.3954,  0.8339,  0.2443,
         -1.6820, -0.4767, -0.6974,  0.0771]])

In [15]:
batch, length, dim = tr.size()

In [12]:
tr.view(2, 1, -1 )

tensor([[[ 1.4779, -1.9527,  0.5818,  0.7369, -1.5111,  0.6199,  1.1163,
           0.8683, -0.6130,  2.4811, -0.9924, -0.4231]],

        [[-1.0748,  0.0165, -0.1008,  0.1572,  0.9345, -0.3954,  0.8339,
           0.2443, -1.6820, -0.4767, -0.6974,  0.0771]]])

In [17]:
dim

4

In [8]:
indices = torch.full([2,5], 0, dtype=torch.bool)

In [11]:
torch.zeros((2,5, 5), dtype=torch.float32)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [10]:
indices.size(0)

2

In [16]:
torch.randint(1, 4, (1,)).item()

2

In [19]:
int(2/(1/6))

12

In [30]:
prob_mat = torch.full([10], 0.15)
prob_mat

tensor([0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
        0.1500])

In [36]:
labels = torch.tensor([2,4, 1, 2, 4, 4, 0, 1, 2, 3,])
labels

tensor([2, 4, 1, 2, 4, 4, 0, 1, 2, 3])

In [37]:
pad_mask = labels.eq(3)
pad_mask

tensor([False, False, False, False, False, False, False, False, False,  True])

In [38]:
prob_mat.masked_fill_(pad_mask, value=0.0)

tensor([0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
        0.0000])

In [39]:
prob_mat

tensor([0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500, 0.1500,
        0.0000])

In [40]:
torch.bernoulli(prob_mat, bool())

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
special_token_mask = [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]]

In [42]:
special_token_mask

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]]

In [45]:
for i in range(len(special_token_mask)) :
    special_token_mask[i][1] = 1
    special_token_mask[i][2] = 1

In [46]:
special_token_mask

[[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]]

In [66]:
attention_probs = torch.randn(6,6)
attention_probs

tensor([[ 0.9522, -0.0984, -1.9387,  1.2249,  0.1643, -0.0550],
        [-0.4470, -0.4799,  0.0878, -0.4490,  1.0576, -1.1842],
        [ 0.4580, -2.0434,  0.4104, -0.4424,  0.8317,  0.3443],
        [ 1.8214, -0.2447, -0.2004, -0.4490,  1.3892,  0.9470],
        [-0.1066, -0.6831,  0.5272,  1.2701, -0.6616, -2.5449],
        [ 1.5628,  0.9914,  0.2905,  0.8820,  0.9384, -1.1951]])

In [69]:
attention_probs[0,1:3] = 0*attention_probs[0,1:3]
attention_probs

tensor([[ 0.9522, -0.0000, -0.0000,  1.2249,  0.1643, -0.0550],
        [-0.4470, -0.4799,  0.0878, -0.4490,  1.0576, -1.1842],
        [ 0.4580, -2.0434,  0.4104, -0.4424,  0.8317,  0.3443],
        [ 1.8214, -0.2447, -0.2004, -0.4490,  1.3892,  0.9470],
        [-0.1066, -0.6831,  0.5272,  1.2701, -0.6616, -2.5449],
        [ 1.5628,  0.9914,  0.2905,  0.8820,  0.9384, -1.1951]])

In [64]:
cls_mask = torch.full([6,6], 1, dtype=torch.int)
cls_mask[0,1:3] = 0
cls_mask[1,0] = 0
cls_mask[1,2] = 0
cls_mask[2,0:2] = 0
cls_mask

tensor([[1, 0, 0, 1, 1, 1],
        [0, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [61]:
attention_probs * cls_mask

tensor([[ 1.8271e+00, -0.0000e+00,  4.7968e-01,  1.1799e-02,  1.3656e+00,
          2.8584e-01],
        [-0.0000e+00, -2.7432e+00, -7.9998e-01,  8.7125e-02, -1.6635e-02,
         -1.3530e+00],
        [ 1.6530e-03,  1.6197e-01,  6.0262e-01,  1.7305e+00,  1.2537e+00,
         -4.4238e-01],
        [ 1.0182e+00, -7.4112e-01, -2.5605e-01,  2.0033e-01,  1.6737e+00,
         -4.2202e-01],
        [-6.8350e-01, -1.4268e+00,  1.6192e+00, -6.0694e-02,  1.6461e-01,
         -2.3667e-01],
        [ 4.7730e-01,  2.0785e-02, -4.4153e-01, -1.4774e+00, -9.5424e-01,
         -1.3587e+00]])

In [70]:
pwd

'/home/beomgon/algorithm_test'